haha: default

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

logging:
    config: classpath:log4j2-dev.xml


# 配置服务注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/