spring:
  application:
    name: registry

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://registry:8761/eureka/

server:
  port: 8761