version: '2.1'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql # 数据存储目录
      - ./mysql/script:/docker-entrypoint-initdb.d # 自动初始化脚本目录
      - ./mysql/conf:/etc/mysql/conf.d # 自定义配置文件目录
    environment:
        TZ: "Asia/Shanghai"
        MYSQL_DATABASE: "test"
        MYSQL_USER: "test"
        MYSQL_PASSWORD: "123456"
        MYSQL_ROOT_PASSWORD: "123456"
