version: '2.1'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "/data"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
        TZ: "Asia/Shanghai"
        MYSQL_DATABASE: "test"
        MYSQL_USER: "test"
        MYSQL_PASSWORD: "123456"
        MYSQL_ROOT_PASSWORD: "123456"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "/tmp"

  registry-server:
    image: registry-server
    ports:
      - "8761:8761"
    expose:
      - 8761

  config-server:
      image: config-server
      ports:
        - "8888:8888"
      expose:
        - 8888
      depends_on:
        - "registry-server"
      extra_hosts:
       - "registry-server-host:172.168.2.69"

  order-service:
      image: order-service
      ports:
        - "9999:9999"
      expose:
        - 9999
      depends_on:
        - "registry-server"
        - "config-server"
      extra_hosts:
       - "registry-server-host:172.168.2.69"
       - "mysql-host:172.168.2.16"
       - "rabbitmq-host:172.168.2.16"

  user-service:
      image: user-service
      ports:
        - "7777:7777"
      expose:
        - 7777
      depends_on:
        - "registry-server"
        - "config-server"
      extra_hosts:
       - "registry-server-host:172.168.2.69"
       - "mysql-host:172.168.2.16"
       - "rabbitmq-host:172.168.2.16"