version: '2.1'
services:
  registry-server:
    image: registry-server
    ports:
      - "8761:8761"
    expose:
      - 8761

  config-server:
      image: config-server
      ports:
        - "8888:8888"
      expose:
        - 8888
      extra_hosts:
       - "registry:127.0.0.1"

  order-service:
      image: order-service
      ports:
        - "9999:9999"
      expose:
        - 9999
      extra_hosts:
       - "registry:127.0.0.1"
       - "mysql-host:172.168.2.16"
       - "rabbitmq-host:172.168.2.16"