version: '2.1'
services:
  api-gateway:
      image: api-gateway
      ports:
        - "80:80"
      expose:
        - 80
      depends_on:
        - "registry-server"
        - "config-server"
      extra_hosts:
       - "registry-server:172.168.2.69"
