version: '2.1'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "/data"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
        TZ: "Asia/Shanghai"
        MYSQL_DATABASE: "test"
        MYSQL_USER: "test"
        MYSQL_PASSWORD: "123456"
        MYSQL_ROOT_PASSWORD: "123456"
