version: '2.1'
services:
  order-service:
      image: order-service
      ports:
        - "9999:9999"
      expose:
        - 9999
      extra_hosts:
       - "registry:127.0.0.1"
       - "rabbitmq-host:127.0.0.1"
       - "config-host:127.0.0.1"