version: '2.1'
services:
  registry-server:
    image: registry-server
    ports:
      - "8761:8761"
    expose:
      - 8761

  config-server:
      image: config-server
      ports:
        - "8888:8888"
      expose:
        - 8888
      extra_hosts:
       - "registry:localhost"