version: '2.1'
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql # 数据存储目录
      - ./mysql/script:/docker-entrypoint-initdb.d # 自动初始化脚本目录
      - ./mysql/conf:/etc/mysql/conf.d # 自定义配置文件目录
    environment:
        TZ: "Asia/Shanghai"
        MYSQL_DATABASE: "test"
        MYSQL_USER: "test"
        MYSQL_PASSWORD: "123456"
        MYSQL_ROOT_PASSWORD: "123456"
    network_mode: "host"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "/tmp"
    network_mode: "host"

  registry-server:
    image: registry-server
    restart: always
    ports:
      - "8761:8761"
    expose:
      - 8761
    network_mode: "host"

  config-server:
      image: config-server
      restart: always
      ports:
        - "8888:8888"
      expose:
        - 8888
      depends_on:
        - "registry-server"
      extra_hosts:
       - "registry-server:172.168.2.69"
      network_mode: "host"

  api-gateway:
      image: api-gateway
      restart: always
      ports:
        - "80:80"
      expose:
        - 80
      depends_on:
        - "registry-server"
        - "config-server"
      extra_hosts:
       - "registry-server:172.168.2.69"
      network_mode: "host"

  user-service:
      image: user-service
      restart: always
      ports:
        - "7777:7777"
      expose:
        - 7777
      depends_on:
        - "registry-server"
        - "config-server"
      extra_hosts:
       - "registry-server:172.168.2.69"
       - "mysql-server:172.168.2.69"
       - "rabbitmq-server:172.168.2.69"
      network_mode: "host"

  user-consumer-ribbon:
      image: user-consumer-ribbon
      restart: always
      ports:
        - "9991:9991"
      expose:
        - 9991
      depends_on:
        - "registry-server"
        - "config-server"
        - "user-service"
      extra_hosts:
       - "registry-server:172.168.2.69"
       - "mysql-server:172.168.2.69"
       - "rabbitmq-server:172.168.2.69"
      network_mode: "host"