spring:
  application:
    name: api-gateway
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config


server:
  port: 80

zuul:
  ignoredServices: '*'
  host:
    max-total-connections: 200
    max-per-route-connections: 20

  routes:
    user-service:
      path: /users/**
      serviceId: user-service
      stripPrefix: false
      sensitiveHeaders:










