spring:
  application:
    name: user-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
      name: cloud-config
      profile: dev


server:
  port: 7777


management:
  security:
    enabled: false


# mybatis配置
mybatis:
  type-aliases-package: com.nextyu.domain
  mapper-locations: classpath*:mapper/*.xml












