spring:
  application:
    name: user-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config


server:
  port: 7777


# 配置服务注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/





