spring:
  application:
    name: user-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config



server:
  port: 7777


# mybatis配置
mybatis:
  type-aliases-package: com.nextyu.domain
  mapper-locations: classpath*:mapper/*.xml









