spring:
  application:
    name: order-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
      name: cloud-config
      profile: dev
      uri: http://127.0.0.1:8888



server:
  port: 9999


management:
  security:
    enabled: false












