spring:
  application:
    name: order-service
  cloud:
    config:
      fail-fast: true
      name: cloud-config
      profile: dev
      uri: http://172.168.2.69:8888


server:
  port: 9999


management:
  security:
    enabled: false











