spring:
  application:
    name: order-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
      name: cloud-config
      profile: dev
      uri: http://config-host:8888



server:
  port: 9999


management:
  security:
    enabled: false

# 配置服务注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/










