spring:
  application:
    name: order-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
      name: cloud-config
      profile: dev



server:
  port: 9999


management:
  security:
    enabled: false












