spring:
  application:
    name: monitoring-server
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
      name: cloud-config
      profile: dev





management:
  security:
    enabled: false







