spring:
  application:
    name: user-consumer-ribbon
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
      name: cloud-config
      profile: dev

server:
  port: 9991


management:
  security:
    enabled: false







