spring:
  application:
    name: user-consumer-feign
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
      name: cloud-config
      profile: dev

server:
  port: 9992


management:
  security:
    enabled: false







