spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nextyu/spring-cloud-simple-demo.git
          search-paths:/config-repo
          timeout: 30000


server:
  port: 8888


# 配置服务注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/





